kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "synology-csi.fullname" . }}-node-role
subjects:
  - kind: ServiceAccount
    name: {{ include "synology-csi.fullname" . }}-node-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "synology-csi.fullname" . }}-node-role
  apiGroup: rbac.authorization.k8s.io
