{{- if .Values.controller.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "synology-csi.node.serviceAccountName" . }}
  labels:
    {{- include "synology-csi.labels" . | nindent 4 }}
  {{- with .Values.node.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
