---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-nfs-storage
provisioner: csi.san.synology.com
parameters:
  protocol: "nfs" # required for nfs protocol
  mountPermissions: '0777'
  # dsm: "1.1.1.1"
  # location: '/volume1'
mountOptions:
  - nfsvers=4 #3,4,4.1
reclaimPolicy: Delete
allowVolumeExpansion: true
