kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ include "synology-csi.fullname" . }}-controller
  labels:
    {{- include "synology-csi.labels" . | nindent 4 }}  
spec:
  serviceName: "{{ include "synology-csi.fullname" . }}-controller"
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "synology-csi.fullname" . }}-controller
  template:
    metadata:
      {{- with .Values.controller.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}    
      labels:
        app: {{ include "synology-csi.fullname" . }}-controller
    spec:
      serviceAccountName: {{ include "synology-csi.fullname" . }}-controller-sa
      hostNetwork: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}     
      securityContext:
        {{- toYaml .Values.controller.podSecurityContext | nindent 8 }}         
      containers:
        - name: csi-provisioner
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: {{ index .Values "controller" "csi-provisioner" "image" "repository" }}:{{ index .Values "controller" "csi-provisioner" "image" "tag" }}
          args:
            - --timeout=60s
            - --csi-address=$(ADDRESS)
            - --v=5
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: {{ index .Values "controller" "csi-provisioner" "image" "pullPolicy" }}
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-attacher
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: {{ index .Values "controller" "csi-attacher" "image" "repository" }}:{{ index .Values "controller" "csi-attacher" "image" "tag" }}
          args:
            - --v=5
            - --csi-address=$(ADDRESS)
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: {{ index .Values "controller" "csi-attacher" "image" "pullPolicy" }}
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-resizer
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: {{ index .Values "controller" "csi-resizer" "image" "repository" }}:{{ index .Values "controller" "csi-resizer" "image" "tag" }}
          args:
            - --v=5
            - --csi-address=$(ADDRESS)
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: {{ index .Values "controller" "csi-resizer" "image" "pullPolicy" }}
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-plugin
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: {{ index .Values "controller" "csi-plugin" "image" "repository" }}:{{ default .Chart.AppVersion (index .Values "controller" "csi-plugin" "image" "tag") }}
          args:
            - --nodeid=NotUsed
            - --endpoint=$(CSI_ENDPOINT)
            - --client-info
            - /etc/synology/client-info.yml
            - --log-level=info
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: {{ index .Values "controller" "csi-plugin" "image" "pullPolicy" }}
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
            - name: client-info
              mountPath: /etc/synology
              readOnly: true
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}              
      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: client-info
          secret:
            secretName: {{ .Values.clientInfoSecretName }}
