{{- range .Values.storageClasses }}

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
  annotations:
    {{- if .isDefault }}
    storageclass.kubernetes.io/is-default-class: "true"
    {{- end }}
provisioner: csi.san.synology.com
parameters:
  {{- toYaml .parameters | nindent 2}}
# if all params are empty, synology CSI will choose an available location to create volume
# parameters:
#   dsm: '1.1.1.1'
#   location: '/volume1'
#   fsType: 'ext4'
reclaimPolicy: {{ .reclaimPolicy }}
allowVolumeExpansion: true
---
{{- end }}
