{{- if .Values.snapshotter.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "synology-csi.fullname" . }}-snapshotter-role
subjects:
  - kind: ServiceAccount
    name: {{ include "synology-csi.fullname" . }}-snapshotter-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "synology-csi.fullname" . }}-snapshotter-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
